// NPM_Publication_test/my-angular-project-react/my-angular-project/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  doSomething() {
    console.log('Icon Clicked');
  }
}

<h1>Hello Lit</h1>

<my-panel-jffp title="My normal angular Profile" icon="1" opened (icon-click)="doSomething()">
</my-panel-jffp>

// NPM_Publication_test/my-react-project/src/App.tsx
import { useState } from 'react'
import { MyPanelJffpReactExport } from 'my-panel-jffp-react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <MyPanelJffpReactExport title='My React Profile' icon='1' onIconClick={() => console.log('ICON CLicked')}>
        text
      </MyPanelJffpReactExport>
    </div>
  )
}

export default App
